### ISSUE TITLE
Fabric Seasons Compatibility

### ISSUE THREAD

**Issue by PPMDJ** [TheDeathlyCow/scorchful#30]
Simply put, Scorchful should definitely interact with fabric seasons like Frostful does. We can have heat affect the player in all sorts of biomes in the summer time, and make hot deserts hotter! 

"Limits of survival are set by climate, those long drifts of change which a generation may fail to notice. And it is the extremes of climate which set the pattern. Lonely, finite humans may observe climatic provinces, fluctuations of annual weather and occasionally may observe such things as “This is a colder year than I’ve ever known.” Such things are sensible. But humans are seldom alerted to the shifting average through a great span of years. And it is precisely in this alerting that humans learn how to survive on any planet. They must learn climate."

-Frank Herbert, Children of Dune

**Comment by TheDeathlyCow** [comment]
Oh yeah, this is definitely needed. Serene Seasons should also be integrated when Scorchful updates to 1.20.4.
