### ISSUE TITLE
Dogs can't pant

### ISSUE THREAD

**Issue by Hyomoto** [TheDeathlyCow/scorchful#34]
**Describe the bug**
This may be more of a side interaction with mods like Doggy Talents https://github.com/DashieDev/DoggyTalentsNext.  However, it highlights a major oversight in the approach taken: anything that isn't human seemingly has no way to recover from heat-related injuries.  In this specific case, a dog will die from heat injuries but because of how DTN works, they are only incapacitated... except now they can also never recover because they have no way to reduce their heat and continue to sustain damage.  I'm not sure if this is specific to how DTN treats dogs or if this happens to all entities and it's just harder to notice.

It may just be an oversight that things that are set on fire take heat damage as well, while this is somewhat comedic for the player it's more of a problem for mobs who have no vectors to cool off.

**To Reproduce**
1. Set a dog on fire.
2. Put the dog out.
3. Watch them die from heat stroke.

**Expected behavior**
Mobs should either be able to recover from heat injuries, for example by submerging them, or they shouldn't be able to be affected at all.

**Game information (please complete)**
- MC Version 1.20.1
- Loader Fabric 0.15.7

**Logs**
Please provide a log, particularly in the case of crashes
[latest.log](https://github.com/TheDeathlyCow/scorchful/files/14629724/latest.log)

**Additional context**
None.

**Comment by TheDeathlyCow** [comment]
Thanks for the feedback! Right now wetness cooling is just ticked on the player -- but I think it would make sense to make it tick on all temperature aware entities.
