### ISSUE TITLE
Campfire Heating

### ISSUE THREAD

**Issue by CasualJeremy** [TheDeathlyCow/scorchful#38]
Campfires cause entities to overheat way too fast. Any entity near a campfire seems to start dying from overheating within 10 seconds of being remotely near it.

Either nerf the campfire heating and/or include a config option that allows users to set their own values.

**Comment by TheDeathlyCow** [comment]
are you using frostiful? if so, what version?

**Comment by CasualJeremy** [comment]
I am, Frostiful 1.0.4 I believe

**Comment by CasualJeremy** [comment]
But testing with the newest version, 1.0.6, seems the have the same result

**Comment by TheDeathlyCow** [comment]
I cannot replicate with Frostiful 1.0.6, in neither the Nether nor the Overworld. This was a known issue in Frostiful 1.0.4 though, and it has been fixed. 
![image](https://github.com/TheDeathlyCow/scorchful/assets/53499406/610f047f-f315-4cad-a6ad-3a6ddc53cbc4)

**Comment by TheDeathlyCow** [comment]
Let me know if you find anything. In the mean time, I will close this issue.
