### ISSUE TITLE
Compatibility with Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by Delfonso** [TheDeathlyCow/scorchful#42]
would be nice if you add compatibility to this new vercion of farmers delight: https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated

**Comment by TheDeathlyCow** [comment]
Just had a quick look at this mod. The mod ID and item IDs match - so drinkable items should work out of the box. I will look into it a bit more later.

**Comment by TheDeathlyCow** [comment]
I can confirm that it technically works - only the tool tip does not show up. This is due to the that version of the mod fully overriding item tooltips, so my mixin does not get to be called. To me, this is more of an issue on their end. I made a report in MehVahdJukaar/FarmersDelight#12 for this.
