### ISSUE TITLE
Compat with Thirst Was Taken

### ISSUE THREAD

**Issue by IntM4rco** [TheDeathlyCow/scorchful#47]
Hi, I know your mod is compatible with Dehydration however when I tried it I didn't like how thirst works with it, so please could you make Thirst Was Taken compatible, it's more balanced and also compatible with for example Farmer Delight and Create, so that would be very nice use it together with your mod. 

https://modrinth.com/mod/thirst-was-taken

**Comment by TheDeathlyCow** [comment]
Thanks for the suggestion, I do like the look of that mod! However, it is a Forge mod so it is fundamentally incompatible with Scorchful at the loader level. If there are other thirst similar mods available for Fabric or Quilt then I'd be happy to add a compat for them.
