### ISSUE TITLE
Heat Visions

### ISSUE THREAD

**Issue by TheDeathlyCow** [TheDeathlyCow/scorchful#49]
Add fake wells and ponds that appear to players with Heat Stroke. I have no clue how I will get this to work, so may take some fenagling. 

Checklist:
- [x] Determine how to create fake, temporary structures. Many involve creating a multi-part entity like the Ender Dragon.
- [x] Write an algorithm to spawn visions around heat stroked players based on location info 
- [x] Desert Well vision (may wait for Flywheel to update before implementing this)
- [x] Husk vision
- [x] Boat vision
- [x] Poppy vision
- [x] Have visions disappear when a Heat Stroked player approaches them 
- [x] Make Heat Stroke start at a lower temperature (maybe like 75%)
- [x] Add event for heat stroke approach (to be used for Mirage spawning)

**Comment by IntM4rco** [comment]
I can't wait, what a great feature.

**Comment by IntMarco** [comment]
Hell YEAH!!!
