### ISSUE TITLE
[1.20.1] Drinking water doesn't reduce heat or add to the water bar in nether

### ISSUE THREAD

**Issue by Reshy** [TheDeathlyCow/scorchful#55]
**Describe the bug**
Water Skins/Water Bottles aren't refilling the hydration bar, so they don't actually cool you down in the nether.

**To Reproduce**
1. Go to the Nether
2. Get overheated
3. Drink Water
4. Nothing happens.

**Expected behavior**
From the way the game describes it, the water skin and water bottles ought to cool you down, but that doesn't seem to be the case, you also don't passively sweat either in the nether so likely there's a bug with the sweat system.  Touching water like from a crimson lily fully saturates your hydration bar but beyond that there's no cooling down besides to lug around some ice blocks.  Can't even stand in a cauldron.

**Game information (please complete)**
- MC Version (1.20, 1.20.1, etc):  1.20.1
- Loader (Fabric/Quilt or NeoForge with Connector):   0.15.10

**Logs**
N/A

**Additional context**
Starting drinking a water skin:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/1e044564-c8ef-452d-9f3c-f7c4b57e2f68)

Finished drinking the entire waterskin:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/3fafee2e-0c21-4243-8c97-99aed5270c7a)

Touch Crimson Lily with a crumb of water dew on it:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/5ec612a7-f1a6-4e00-9658-016ff31c9da6)

Behavior occurs even when actively dying from heat stroke:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/15c27d57-5bc5-4484-8958-225c678ef525)

![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/a9c19abe-cf33-4154-8fda-12a3dec793a1)

Heat stroke still progresses even when standing in water, no hydration:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/10aa6cd7-bb7e-48fe-ac9d-5d2d02a28ffd)
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/cbcf10ae-17bd-4ac4-9dd3-b5d7580a9714)

Only complete submersion in water actually fills the hydration meter:
![image](https://github.com/TheDeathlyCow/scorchful/assets/2096384/7e7ef590-91a3-4900-85b5-39a03d91a188)

**Comment by TheDeathlyCow** [comment]
Just curious, does this still happen in dark environments? I think the light from that fire may be causing you to dry out before you lose any meaningful amount of temperature.

**Comment by TheDeathlyCow** [comment]
Going to assume that that was the cause. For now, removing that mechanic (and also made some adjustments to block light heat). Feel free reopen if this issue persists in 0.6.2.

**Comment by Reshy** [comment]
Seems like it's fixed from my personal testing.  Drinking Water, standing in water, etc. increases the water meter like it's supposed to.
