### ISSUE TITLE
Command to disable Effects

### ISSUE THREAD

**Issue by Exokyhh** [TheDeathlyCow/scorchful#59]
**Is your feature request related to a problem? Please describe.**
Yes it is! I really like this mod, but, there is a problem. In my modpack, I have origins (https://modrinth.com/mod/origins), the Blazeborn, for example, will spawn in the nether, and he is by default immune to all fire damage. His gameplay doesn't make any sense, if every time he touches lava (from which he is immune), he gets all those effects and the dizzy screen effect. 

**Describe the solution you'd like**
What would be good, is to have a command* to ignore the temperature effect (cold or heat, separately). There is a command to set the temperature, but I can't run a command every few ticks to reset the temperature of the blazeborn. It would be better to have a command to completely disable the effect.
(of course the command should be reversible, since origins can be changed)

*(the command should support @ formats, like @s, @p....)

**Describe alternatives you've considered**
Mhhh not really other options come to my mind. The command is the simplest since it has to run differently per player. Once the player chooses an origin, I can automatically run a command and disable heat and/or cold effects.

**Additional context**
Compatibility with the Merling origin too? As he is unable to breathe on land (unless it's raining), it would be cool if he could still breathe for the seconds that he is wet after getting out of the water (although this would be harder to implement I think, since it has to be an explicit compatibility with the mod? I'm not a java mod developer lol)

**Comment by TheDeathlyCow** [comment]
Have you tried installing Thermoo Patches? It has an explicit compatibility patch for the Blazeborn Origin. https://modrinth.com/mod/origins

It literally just released yesterday so I haven't gotten around to updating the mod page yet.

**Comment by Exokyhh** [comment]
Oohhh lol didn't see that! Cool

**Comment by TheDeathlyCow** [comment]
I will say though, the current patch is a little barebones. It just makes the Blazeborn completely immune to active temperature changes. I plan to add some more functionality to Thermoo in the future to make the Blazeborn actually *benefit* from heat, not just be immune to it. Same for the Snow Golem (in Mob Origins). I also like the Merling idea, it is something I can also add to Thermoo Patches.

**Comment by Exokyhh** [comment]
What would be cool (maybe this should be a feature request) is to add immunity from fire, when still wet. So that, for example, if the Phantom gets out of water, while still drying, he can't catch fire from the sun (it's one of his main weaknesses)

**Comment by TheDeathlyCow** [comment]
With the Phantom origin, I think that could be weird if the Phantom doesn't burn, but Zombies and Skeletons still burn when wet. Might be better as a general thing to implement to prevent the undead from burning when wet.

**Comment by Exokyhh** [comment]
Indeed. Will wait for the implementation (if you decide to add it) :)

**Comment by TheDeathlyCow** [comment]
Final note on this issue specifically addressing the suggestion of a command:

Temperature effects are fully data driven and can be supplied in a datapack. They use predicates to determine which entities can be affected by certain temperature effects so you could fiddle with that using the scoreboard (or power predicates in Origins) to disable heat effects for certain players. 

See this page on the Thermoo developer wiki on the format of temperature effects:

https://github.com/TheDeathlyCow/thermoo/wiki/Temperature-Effects-(Mods-and-Datapacks)

And this folder in Scorchful contains all the base temperature effects in 1.20.1 (I made some changes to it in 1.20.4):

https://github.com/TheDeathlyCow/scorchful/tree/1.20.1/src/main/resources/data/scorchful/thermoo/temperature_effects
