### ISSUE TITLE
Thirst Feature Compatibility

### ISSUE THREAD

**Issue by rjshadowface** [TheDeathlyCow/scorchful#65]
I am using your mods in a Forge + Fabric modlist for 1.20.1 using Syntra and I would like very much to be able to combine your amaising mods those with other mods which unfortunately have no Fabric alternatives yet.

Could you please make it posible to disable the build in thirst functionality via config file to make it compatible with other thirst mods like "Thirst Was Taken" (Forge) which has very nice integration with the Create mod.

Here is a link to the "Thirst Was Taken" mod:
https://www.curseforge.com/minecraft/mc-mods/thirst-was-taken

**Comment by TheDeathlyCow** [comment]
Scorchful is not a Forge mod, and as stated on the mod page support for Sinytra connector is not offered at this time. As far as I can tell, there is no Fabric or Quilt version of this mod, so support for it will not be made.
