### ISSUE TITLE
✨[Feature Request] Seasons would affect temperatures

### ISSUE THREAD

**Issue by User4716** [TheDeathlyCow/scorchful#68]
It would be nice if this mod had compatibility with "Fabric seasons" (or other season mods) 
So when it's winter, you would gain heat slower. The effect could be seen in the "Frostful" mod as well, so if it's summer, I would freeze slower.

Also a little notice, it would be more realistic if during nights all overworld biomes would be a little cooler. That's how it works in real life. For example deserts are not hot during the night.

I hope these ideas are worth your consideration! 💝

**Comment by TheDeathlyCow** [comment]
Hi, thanks for the suggestion. It's a good one! Which is why it's already be done, you just need to install Thermoo Patches: https://modrinth.com/mod/thermoo-patches
