### ISSUE TITLE
Any plans to include Tough As Nails compatibility? 

### ISSUE THREAD

**Issue by FormBurden** [TheDeathlyCow/scorchful#79]
~~Since this mod does support Serene Seasons, are there any plans to integrate support for Tough As Nails at all?~~

Geez read everywhere until I finally saw that you have no plans for EnvironmentZ or Tough As Nails. I guess the bottom paragraph still stands.

If not, possibly a config setting that could turn off certain features, such as the thirst mechanic, and/or heating. This could be a feature so instead of having actual compatibility, you could turn off certain mechanics if you'd rather only want to use a different mods thirst/temp mechanic. I know some other mods have a config to disable a feature. Just a thought.

For 1.21 Minecraft

Thanks for your time!

**Comment by TheDeathlyCow** [comment]
No. Tough As Nails and EnvironmentZ are fundamentally different temperature mods. There is no point in trying to run them together with Scorchful and Frostiful: pick one or the other, but not both. If you want the more hardcore thirst mechanic offered by Tough As Nails, Scorchful integrates with Dehydration: https://modrinth.com/mod/dehydration

**Comment by FormBurden** [comment]
Right, I ended up just continuing with Dehydrate instead.
