### ISSUE TITLE
Sand piles causing snow to appear on the side of blocks with some resource packs

### ISSUE THREAD

**Issue by Yoni664** [TheDeathlyCow/scorchful#84]
**Is your feature request related to a problem? Please describe.**
I think that the sand layers are cool but Im trying to use a RP that add side layers to the snow layers and it seems that sand layers of this mod are affected by this effect too, giving a bad looking result!

**Describe the solution you'd like**
Maybe adding compatibility with the RP that I tried to use

**Describe alternatives you've considered**
I just tried to change between two RP and both had problems with the mod. Later Im gonna try to edit the RP trying to find a solution. I dont know if maybe the problem is that both RP are outdated

**Additional context**
![image](https://github.com/user-attachments/assets/2f3921a3-4059-469d-83d9-8c65e25fbaa2)
With Snow and moss overhangs - Deep Origins Overlays https://modrinth.com/resourcepack/deep-origins-snow-moss

![image](https://github.com/user-attachments/assets/f0a74d7e-b6f5-45fe-9387-d6394cc5fac1)
With Snowier Snow Layers https://modrinth.com/resourcepack/snowier-snow-layers!

![image](https://github.com/user-attachments/assets/7455ec92-d14a-47e8-a2bf-74f4d1bfceff)
With Snowiest Snow https://modrinth.com/resourcepack/snowiest-snow/version/1.19.3

**Comment by TheDeathlyCow** [comment]
i cannot add compatibility to these resource packs, that is up to the creator of said resource packs. but i can maybe fix the snow appearing on the sides of blocks

**Comment by Yoni664** [comment]
Thx for this! <3
