### ISSUE TITLE
Heat Stroke visual effect disorder

### ISSUE THREAD

**Issue by EtoKobato** [TheDeathlyCow/scorchful#88]
**Describe the bug**
Heat Stroke visual effect with [scorchful](https://github.com/TheDeathlyCow/scorchful) 
PHOTOSENSITIVITY/EPILEPSY SEIZURES

**To Reproduce**
1. Start New Game.
2. Set `Serene Season` to `Summer` (`/season set mid_summer`).
3. Stand and wait for the max body temperature.
4. Effect eg `**Heat Stroke**` comes with visual disorder.

**Expected behavior**
Normal visual effect should show up

**Game information (please complete)**
- MC Version (1.21.1):
- Loader (Fabric 0.5.16): 
- Serene Seasons
- Sodium
- Sodium Extra
- Iris

**Logs**
[Is not crash](https://gist.github.com/EtoKobato/2ceee0bc63ca666d62c43f16ba9c23c7)

**Additional context**
![GIF](https://github.com/user-attachments/assets/02f5a236-6e68-4830-8dfc-67b7dd8afe5a)

**Comment by TheDeathlyCow** [comment]
With the mods listed I cannot replicate this issue. It's probably a result of one of your other HUD or rendering mods. If needed you can disable the effect in the config, or maybe adjust it to remove the blur pass in a resource pack.

**Comment by EtoKobato** [comment]
Ok thanks, and will AMD cause this?

**Comment by TheDeathlyCow** [comment]
I have no reason to think so but I don't have an AMD graphics card so I can't test that.

**Comment by EtoKobato** [comment]
Thanks,driver and shader issue for me.
Update driver and change shader pack setting.
