### ISSUE TITLE
Config for items that give thirst

### ISSUE THREAD

**Issue by PixitOwO** [TheDeathlyCow/scorchful#89]
Hello! I love the mod so far and the way you have implemented temperature into minecraft, literally the only complaint is the ability to add specific items, for example from Create: Food, to a config to give them Hydrating bonus or other benefits from drinking them. I personally am not super knowledgeable about the event that triggers when you consume items, but would love to have something configurable for modpack makers!

**Comment by TheDeathlyCow** [comment]
Hey there, you can already do this in your mod pack datapack with datapack tags. Use the water tags for thirst and cooling food tags for frozen foods like ice creams. They're documented on the wiki: https://github.com/TheDeathlyCow/scorchful/wiki/Tags#item-tags
